"""add photo rate limiting fields to user

Revision ID: 573ff5ce6812
Revises: b53bda6fba5d
Create Date: 2026-02-24 10:11:31.524373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '573ff5ce6812'
down_revision: Union[str, None] = 'b53bda6fba5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('photo_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user', sa.Column('last_photo_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_photo_date')
    op.drop_column('user', 'photo_count')
    # ### end Alembic commands ###
