"""Initial schema with OAuth support

Revision ID: b53bda6fba5d
Revises:
Create Date: 2026-02-18 17:14:07.319018

Rewritten September 16, 2026.

This revision was originally autogenerated against a database that
``SQLModel.metadata.create_all()`` had already built at app startup, so Alembic
saw no missing tables and produced only an index tweak:

    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)

The consequence was that no migration had ever created a table. The schema
existed only because create_all() ran on every cold start, and
``alembic upgrade head`` on a fresh database failed immediately with
"no such index: ix_user_email". Removing create_all() from the startup path
exposed that.

This now creates the real baseline schema. The revision id is deliberately
unchanged: a database already stamped at a later revision (such as production)
sees no new work on ``upgrade`` and needs no manual stamping. The photo
rate-limiting columns stay in 573ff5ce6812 so that revision remains valid.

Rewriting an applied revision breaks the usual immutability rule, and it does
change one thing for an existing database: ``downgrade`` here now drops every
table, where before it only restored an index. That is the honest behaviour for
a baseline revision - ``downgrade base`` means "no schema" - but it makes
``alembic downgrade base`` destructive on a populated database where previously
it was merely incoherent, leaving every table in place while telling Alembic the
database was empty, so the next ``upgrade`` would fail. Nothing in CI runs
``downgrade``; take a backup before running it anywhere holding real data.

The alternative was squashing to a new revision id, which would have required a
manual ``alembic stamp`` against production before this could merge. That was
judged the worse trade.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b53bda6fba5d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the baseline schema."""
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('google_id', sa.String(), nullable=True),
        sa.Column('display_name', sa.String(), nullable=True),
        sa.Column('picture_url', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_google_id'), 'user', ['google_id'], unique=True)

    op.create_table(
        'daily_check_in',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('checkin_date', sa.Date(), nullable=False),
        sa.Column('weight', sa.Float(), nullable=True),
        sa.Column('trained', sa.Boolean(), nullable=False),
        sa.Column('steps', sa.Integer(), nullable=True),
        sa.Column('protein_met', sa.Boolean(), nullable=False),
        sa.Column('notes', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'checkin_date'),
    )
    op.create_index(
        op.f('ix_daily_check_in_user_id'), 'daily_check_in', ['user_id'], unique=False
    )
    op.create_index(
        op.f('ix_daily_check_in_checkin_date'), 'daily_check_in', ['checkin_date'], unique=False
    )

    op.create_table(
        'foodlog',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('checkin_id', sa.Integer(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('calories', sa.Float(), nullable=True),
        sa.Column('protein_g', sa.Float(), nullable=True),
        sa.Column('carbs_g', sa.Float(), nullable=True),
        sa.Column('fat_g', sa.Float(), nullable=True),
        sa.Column('logged_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['checkin_id'], ['daily_check_in.id']),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_foodlog_user_id'), 'foodlog', ['user_id'], unique=False)
    op.create_index(op.f('ix_foodlog_checkin_id'), 'foodlog', ['checkin_id'], unique=False)

    op.create_table(
        'weightentry',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('checkin_id', sa.Integer(), nullable=True),
        sa.Column('for_date', sa.Date(), nullable=False),
        sa.Column('weight_kg', sa.Float(), nullable=False),
        sa.Column('note', sa.String(), nullable=True),
        sa.Column('logged_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['checkin_id'], ['daily_check_in.id']),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_weightentry_user_id'), 'weightentry', ['user_id'], unique=False)
    op.create_index(op.f('ix_weightentry_checkin_id'), 'weightentry', ['checkin_id'], unique=False)
    op.create_index(op.f('ix_weightentry_for_date'), 'weightentry', ['for_date'], unique=False)

    op.create_table(
        'workout',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('checkin_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('started_at', sa.DateTime(), nullable=False),
        sa.Column('note', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['checkin_id'], ['daily_check_in.id']),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_workout_user_id'), 'workout', ['user_id'], unique=False)
    op.create_index(op.f('ix_workout_checkin_id'), 'workout', ['checkin_id'], unique=False)

    op.create_table(
        'exerciseset',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('workout_id', sa.Integer(), nullable=False),
        sa.Column('exercise_name', sa.String(), nullable=False),
        sa.Column('reps', sa.Integer(), nullable=False),
        sa.Column('weight_kg', sa.Float(), nullable=True),
        sa.Column('rpe', sa.Float(), nullable=True),
        sa.Column('performed_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['workout_id'], ['workout.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_exerciseset_workout_id'), 'exerciseset', ['workout_id'], unique=False)

    op.create_table(
        'nutriententry',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('food_log_id', sa.Integer(), nullable=False),
        sa.Column('calories', sa.Float(), nullable=True),
        sa.Column('protein_g', sa.Float(), nullable=True),
        sa.Column('carbs_g', sa.Float(), nullable=True),
        sa.Column('fat_g', sa.Float(), nullable=True),
        sa.Column('fiber_g', sa.Float(), nullable=True),
        sa.Column('sugar_g', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['food_log_id'], ['foodlog.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_nutriententry_food_log_id'), 'nutriententry', ['food_log_id'], unique=False
    )


def downgrade() -> None:
    """Drop the baseline schema."""
    op.drop_index(op.f('ix_nutriententry_food_log_id'), table_name='nutriententry')
    op.drop_table('nutriententry')

    op.drop_index(op.f('ix_exerciseset_workout_id'), table_name='exerciseset')
    op.drop_table('exerciseset')

    op.drop_index(op.f('ix_workout_checkin_id'), table_name='workout')
    op.drop_index(op.f('ix_workout_user_id'), table_name='workout')
    op.drop_table('workout')

    op.drop_index(op.f('ix_weightentry_for_date'), table_name='weightentry')
    op.drop_index(op.f('ix_weightentry_checkin_id'), table_name='weightentry')
    op.drop_index(op.f('ix_weightentry_user_id'), table_name='weightentry')
    op.drop_table('weightentry')

    op.drop_index(op.f('ix_foodlog_checkin_id'), table_name='foodlog')
    op.drop_index(op.f('ix_foodlog_user_id'), table_name='foodlog')
    op.drop_table('foodlog')

    op.drop_index(op.f('ix_daily_check_in_checkin_date'), table_name='daily_check_in')
    op.drop_index(op.f('ix_daily_check_in_user_id'), table_name='daily_check_in')
    op.drop_table('daily_check_in')

    op.drop_index(op.f('ix_user_google_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
