"""Verifies that Alembic alone can build the schema the models expect.

The app used to call SQLModel.metadata.create_all() at startup, which masked the
fact that no migration had ever created a table: the "initial schema" revision
had been autogenerated against an already-populated database and contained only
an index tweak. `alembic upgrade head` on a fresh database failed outright.

Now that Alembic is the only schema owner, these tests keep it honest.
"""

import subprocess
import sys
from pathlib import Path

import pytest
from sqlalchemy import create_engine, inspect

API_DIR = Path(__file__).resolve().parents[1]


def _run_alembic(db_path: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, "-m", "alembic", *args],
        cwd=API_DIR,
        env={
            "PATH": "/usr/bin:/bin",
            "DATABASE_URL": f"sqlite:///{db_path}",
            "JWT_SECRET_KEY": "test-secret",
        },
        capture_output=True,
        text=True,
    )


@pytest.fixture
def migrated_db(tmp_path: Path) -> Path:
    """A database built only by running the migrations."""
    db_path = tmp_path / "migrated.db"
    result = _run_alembic(db_path, "upgrade", "head")
    if result.returncode != 0:
        pytest.fail(f"alembic upgrade head failed:\n{result.stdout}\n{result.stderr}")
    return db_path


def _expected_schema() -> dict[str, set[str]]:
    """Tables and columns the models declare."""
    from sqlmodel import SQLModel

    import app.models  # noqa: F401  # registers the tables

    return {
        table.name: {column.name for column in table.columns}
        for table in SQLModel.metadata.sorted_tables
    }


def test_migrations_create_every_table(migrated_db: Path):
    """Every table the models declare exists after migrating a fresh database."""
    engine = create_engine(f"sqlite:///{migrated_db}")
    try:
        actual = set(inspect(engine).get_table_names()) - {"alembic_version"}
        assert actual == set(_expected_schema())
    finally:
        engine.dispose()


def test_migrated_schema_matches_the_models(migrated_db: Path):
    """Column sets match, so the migration history is not drifting from the models."""
    engine = create_engine(f"sqlite:///{migrated_db}")
    try:
        inspector = inspect(engine)
        mismatches = {}
        for table, expected_columns in _expected_schema().items():
            actual_columns = {c["name"] for c in inspector.get_columns(table)}
            if actual_columns != expected_columns:
                mismatches[table] = {
                    "missing": sorted(expected_columns - actual_columns),
                    "unexpected": sorted(actual_columns - expected_columns),
                }
        assert not mismatches, f"Migrated schema differs from the models: {mismatches}"
    finally:
        engine.dispose()


def test_migrations_create_expected_indexes(migrated_db: Path):
    """Indexes the models declare are created, including the unique ones."""
    engine = create_engine(f"sqlite:///{migrated_db}")
    try:
        inspector = inspect(engine)
        user_indexes = {idx["name"]: idx for idx in inspector.get_indexes("user")}

        assert "ix_user_email" in user_indexes
        # SQLite's inspector reports this as 1/0 rather than a bool.
        assert bool(user_indexes["ix_user_email"]["unique"])
        assert "ix_user_google_id" in user_indexes

        assert "ix_foodlog_user_id" in {
            idx["name"] for idx in inspector.get_indexes("foodlog")
        }
    finally:
        engine.dispose()


def test_downgrade_to_base_removes_the_schema(migrated_db: Path):
    """The migration chain is reversible."""
    result = _run_alembic(migrated_db, "downgrade", "base")
    if result.returncode != 0:
        pytest.fail(f"alembic downgrade base failed:\n{result.stdout}\n{result.stderr}")

    engine = create_engine(f"sqlite:///{migrated_db}")
    try:
        remaining = set(inspect(engine).get_table_names()) - {"alembic_version"}
        assert remaining == set()
    finally:
        engine.dispose()
